language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PACKAGE="mirage-ci"
  - EXTRA_ENV="OPAMSOLVERTIMEOUT=600"
  matrix:
  - OCAML_VERSION="4.06" DISTRO="alpine"
  - OCAML_VERSION="4.07" DISTRO="alpine"
